version: '3'

services:
  db:
    image: postgres
  web:
    hostname: web
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000 --settings=api.settings_development
    volumes:
      - .:/code
    depends_on:
      - db
    links:
      - redis
    env_file:
      - .env/development.env
    ports:
     - 8000:8000
    restart: always
  celery:
    hostname: celery
    build: .
    command: celery -A background_worker worker -B -l info
    volumes:
      - .:/code
    depends_on:
      - db
    links:
      - redis
    env_file:
      - .env/development.env
    restart: always
  redis:
    image: redis:3.2-alpine
    restart: always
